// <auto-generated />
namespace IdentityIntPrimaryKey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class testnewcolumninusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testnewcolumninusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202001191223422_test new column in user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
